[package]
name = "entropy_hpc"
version = "0.1.0"
edition = "2021"

[lib]
name = "entropy_hpc_lib"
path = "src/lib.rs"

[dependencies]
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0

